sonar.organization=pw9876
sonar.projectKey=pw9876_packer-docker
sonar.projectName=packer-docker
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/.github/**,**/tests/**,.dockerignore,.gitignore

sonar.scanner.skipJreProvisioning=true
